#!/bin/bash
#-------------------------------------------------------------------------------
# Display code snippets for various languages
# Created in 2019 by Dave Chouinard
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
function_ansible () { 
case $1 in
  blockinfile)
    cat << EOF
- name: insert/update "Match User" configuration block in /etc/ssh/sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User ansible-agent
      PasswordAuthentication no
EOF
    ;;
  command)
    cat << EOF
- name: return motd to registered var
  command: cat /etc/motd
  register: mymotd
EOF
    ;;
  copy)
    cat << EOF
- name: example copying file with owner and permissions
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: 0644"
EOF
    ;;
  cron)
    cat << EOF
- name: Creates a cron file under /etc/cron.d
  cron:
    name: yum autoupdate
    weekday: 2
    minute: 0
    hour: 12
    user: root
    job: "YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate"
    cron_file: ansible_yum-autoupdate
EOF
    ;;
  file)
    cat << EOF
- name :change file ownership, group and mode
  file:
    path: /etc/foo.conf
    owner: foo
    group: foo
    # when specifying mode using octal numbers, add a leading 0
    mode: 0644
- name: remove a file
  file:
    path: /etc/foo.conf
    state: absent
EOF
    ;;
  yum)
    cat << EOF
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - httpd
    - httpd-tools
EOF
    ;;
  *)
    printf "unknown ansible snippet: $1\n"
    exit 1
    ;;
esac
} 

#-------------------------------------------------------------------------------
function_bash () { 
case $1 in
  case)
    cat << "EOF"
case $VAR in
x | y)
  echo "option x or y was passed"
  ;;
*)
  echo "unkown option"
  exit 1
  ;;
esac
EOF
  ;;
  *)
    printf "unknown bash snippet: $1\n"
    exit 1
    ;;
esac
}

#-------------------------------------------------------------------------------
function_markdown () { 
case $1 in
  collapsible)
    cat << EOF
<details><summary>click here</summary>
hidden text here
</details>
EOF
    ;;
  image)
    cat << EOF
![](URL "hover text")
EOF
    ;;
  link)
    cat << EOF
[link text](URL)
EOF
    ;;
  list)
    cat << EOF
* Unordered list can use asterisks
- Or minuses
+ Or pluses
EOF
    ;;
  table)
  cat << EOF
Normal | Center | Right
--- | :---: | ---:
normal text | center text | right text
EOF
  ;;
  task)
  cat << EOF
- [ ] task 1
EOF
    ;;
  *)
    printf "unknown markdown snippet: $1\n"
    exit 1
    ;;
esac
}

#-------------------------------------------------------------------------------
function_python () { 
case $1 in
  print)
  cat << EOF
print "He's got %s eyes and %s hair." % (my_eyes, my_hair)
print "Number is: %d." % my_number
print '%.2f' % my_float
EOF
    ;;
  *)
    printf "unknown python snippet: $1\n"
    exit 1
    ;;
esac
}

#-------------------------------------------------------------------------------
# Handle user options and call the associated function
#-------------------------------------------------------------------------------
case $1 in
a)
  function_ansible "$2"
  ;;
b)
  function_bash "$2"
  ;;
m)
  function_markdown "$2"
  ;;
p)
  function_python "$2"
  ;;
*)
  printf "unknown option: $1\n"
  exit 1
  ;;
esac
